FROM nvidia/cuda:12.8.0-base-ubuntu22.04

ARG PYTHON_VERSION=3.12
ARG FROM_SOURCE=false
ARG EXTRA_DEPS=""
ARG TORCH_VERSION=2.8

RUN apt-get update && apt-get install -y \
    git curl build-essential libgl1 libglib2.0-0 wget ffmpeg libavcodec-dev libavformat-dev libavutil-dev libswscale-dev libavfilter-dev libavdevice-dev \
    && rm -rf /var/lib/apt/lists/*

RUN curl -LsSf https://astral.sh/uv/install.sh | sh
ENV PATH="/root/.local/bin:${PATH}"

RUN uv python install ${PYTHON_VERSION}
ENV UV_PYTHON=${PYTHON_VERSION}

RUN PYDIR=$(find /root/.local/share/uv/python -maxdepth 1 -type d -name "cpython-*") && \
    ln -s "$PYDIR/bin/aquiles-image" /usr/local/bin/aquiles-image

ENV HF_XET_HIGH_PERFORMANCE=1
ENV PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
ENV UV_BREAK_SYSTEM_PACKAGES=1

WORKDIR /app

RUN uv pip install --system --python ${PYTHON_VERSION} \
    torch==${TORCH_VERSION} torchvision \
    && rm -rf /root/.cache/uv

RUN uv pip install --system --python ${PYTHON_VERSION} transformers==5.12.1 git+https://github.com/ModelTC/LightX2V.git git+https://github.com/FredyRivera-dev/LTX-2.git#subdirectory=packages/ltx-core git+https://github.com/FredyRivera-dev/LTX-2.git#subdirectory=packages/ltx-pipelines bitsandbytes accelerate av https://github.com/mjun0812/flash-attention-prebuild-wheels/releases/download/v0.5.4/flash_attn-2.8.3+cu128torch2.8-cp312-cp312-linux_x86_64.whl vllm==0.11.0 \
    && rm -rf /root/.cache/uv

RUN if [ "$FROM_SOURCE" = "true" ]; then \
        uv pip install --system --python ${PYTHON_VERSION} \
            git+https://github.com/huggingface/diffusers.git \
            git+https://github.com/Aquiles-ai/Aquiles-Image.git \
            && rm -rf /root/.cache/uv; \
    else \
        uv pip install --system --python ${PYTHON_VERSION} diffusers==0.38.0 aquiles-image==0.7.2 \
        && rm -rf /root/.cache/uv; \
    fi

RUN if [ -n "$EXTRA_DEPS" ]; then \
        uv pip install --system --python ${PYTHON_VERSION} $EXTRA_DEPS \
        && rm -rf /root/.cache/uv; \
    fi

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

VOLUME ["/root/.cache/huggingface", "/root/.local/share"]

ENTRYPOINT ["/entrypoint.sh"]
CMD ["aquiles-image", "serve"]